name: Python Test Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'  

    - name: Install npm dependencies
      run: npm install

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python test_get_function_data.py
