name: Python Test Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        # Install any other dependencies your project requires:
        # pip install -r requirements.txt
    - name: Run tests
      run: python test_get_function_data.py
